#!/bin/bash

# Ubuntu中需要有nc命令

# route -n 可查询网关地址
# gateway=`echo $SSH_CONNECTION |sed "s/ .*//g"`
gateway=192.168.64.1
# 主机监听的端口号
port=2333

# 上面两个也可以直接放到bashrc里

function loading()
{
    tag=1
    trap "tag=0" 10
    while [ $tag = 1 ];
    do
        [ $tag = 1 ] && echo -en "\r\\ $1 "`[ $# = 2 ] && du -h $2`"      "
        sleep 0.3
        [ $tag = 1 ] && echo -en "\r| $1 "`[ $# = 2 ] && du -h $2`"      "
        sleep 0.3
        [ $tag = 1 ] && echo -en "\r/ $1 "`[ $# = 2 ] && du -h $2`"      "
        sleep 0.3
    done
    echo -e "\r$* "`[ $# = 2 ] && du -h $2`" done    \n"
    sleep 0.2
}

function backup()
{
    cd /
    BACKFILE="backup_`date '+%Y%m%d'`.tar.gz"

    loading "creating backup ..." "$BACKFILE" &
    pid=$!

    sudo tar -cpzf $BACKFILE \
        --exclude=/usr/src/linux-headers* \
        --exclude=/home/*/Project/ \
        --exclude=/home/ubuntu/daily_homework/ \
        --exclude=/home/ubuntu/homework_31/ \
        --exclude=/home/ubuntu/share/ \
        --exclude=/home/*/.cache /usr /home/*/

    kill -10 $pid
}

function send_msg()
{
    if [ x$1 = x"copy" ];then
        cat > ~/remote_cp_tmp
        cat ~/remote_cp_tmp
        echo -n "copy" |nc -w 0 $gateway $port
    elif [ x$1 = x"typora" ];then
        [ $# = 2 ] || exit -1;
        [ x${2##*.} != x"md" ] && exit -1;                                              
        [ -f $2 ] || touch $2; 
        echo -n "`pwd`/$2" > ~/openTypora
        echo -n "typora" |nc -w 0 $gateway $port
    elif [ x$1 = x"backup" ];then
        backup
        loading "send to Mac ..." &
        pid=$!
        echo -n "backup $pid" |nc -w 0 $gateway $port
        wait $pid

    fi
}

send_msg $*
